DO '
BEGIN
	IF NOT EXISTS(SELECT 1 FROM pg_type WHERE TYPNAME=''sb_user_status'') THEN
		CREATE TYPE SB_USER_STATUS AS ENUM (''INACTIVE'', ''ACTIVE'', ''BANNED'');
	END IF;
	
	IF NOT EXISTS(SELECT 1 FROM pg_type WHERE TYPNAME=''sb_session_status'') THEN
		CREATE TYPE SB_SESSION_STATUS AS ENUM (''ACTIVE'', ''EXPIRED'', ''STOLEN'');
	END IF;
	
	IF NOT EXISTS(SELECT 1 FROM pg_type WHERE TYPNAME=''sb_blocker_records_status'') THEN
		CREATE TYPE SB_BLOCKER_RECORDS_STATUS AS ENUM (''ACTIVE'', ''INACTIVE'');
	END IF;
		
	IF NOT EXISTS(SELECT 1 FROM pg_type WHERE TYPNAME=''sb_blocker_attempts_status'') THEN
		CREATE TYPE SB_BLOCKER_ATTEMPTS_STATUS AS ENUM (''ACTIVE'', ''EXPIRED'');
	END IF;
			
	IF NOT EXISTS(SELECT 1 FROM pg_type WHERE TYPNAME=''sb_news_status'') THEN
		CREATE TYPE SB_NEWS_STATUS AS ENUM (''ACTIVE'', ''INACTIVE'');
	END IF;
				
	IF NOT EXISTS(SELECT 1 FROM pg_type WHERE TYPNAME=''sb_prize_categories_status'') THEN
		CREATE TYPE SB_PRIZE_CATEGORIES_STATUS AS ENUM (''ACTIVE'', ''INACTIVE'');
	END IF;
				
	IF NOT EXISTS(SELECT 1 FROM pg_type WHERE TYPNAME=''sb_prize_status'') THEN
		CREATE TYPE SB_PRIZE_STATUS AS ENUM (''WAITING'', ''COMPLETED'');
	END IF;
					
	IF NOT EXISTS(SELECT 1 FROM pg_type WHERE TYPNAME=''sb_petrol_providers_status'') THEN
		CREATE TYPE SB_PETROL_PROVIDERS_STATUS AS ENUM (''ACTIVE'', ''INACTIVE'');
	END IF;
						
	IF NOT EXISTS(SELECT 1 FROM pg_type WHERE TYPNAME=''sb_petrol_deliveries_status'') THEN
		CREATE TYPE SB_PETROL_DELIVERIES_STATUS AS ENUM (''WAITING'', ''COMPLETED'');
	END IF;
							
	IF NOT EXISTS(SELECT 1 FROM pg_type WHERE TYPNAME=''sb_employees_status'') THEN
		CREATE TYPE SB_EMPLOYEES_STATUS AS ENUM (''ACTIVE'', ''INACTIVE'', ''BANNED'');
	END IF;
								
	IF NOT EXISTS(SELECT 1 FROM pg_type WHERE TYPNAME=''sb_client_people_gender'') THEN
		CREATE TYPE SB_CLIENT_PEOPLE_GENDER AS ENUM (''MALE'', ''FEMALE'', ''UNKNOWN'');
	END IF;
									
	IF NOT EXISTS(SELECT 1 FROM pg_type WHERE TYPNAME=''sb_employees_gender'') THEN
		CREATE TYPE SB_EMPLOYEES_GENDER AS ENUM (''MALE'', ''FEMALE'', ''UNKNOWN'');
	END IF;
									
	IF NOT EXISTS(SELECT 1 FROM pg_type WHERE TYPNAME=''sb_petrol_containers_type'') THEN
		CREATE TYPE SB_PETROL_CONTAINERS_TYPE AS ENUM (''E95'', ''E98'', ''ON'', ''LPG'');
	END IF;
										
	IF NOT EXISTS(SELECT 1 FROM pg_type WHERE TYPNAME=''sb_petrol_containers_measurements_type'') THEN
		CREATE TYPE SB_PETROL_CONTAINERS_MEASUREMENTS_TYPE AS ENUM (''PRESSURE'', ''PETROL_LEVEL'');
	END IF;
											
	IF NOT EXISTS(SELECT 1 FROM pg_type WHERE TYPNAME=''sb_acl_rule_type'') THEN
		CREATE TYPE SB_ACL_RULE_TYPE AS ENUM (''ALLOWED'', ''DENIED'');
	END IF;
											
	IF NOT EXISTS(SELECT 1 FROM pg_type WHERE TYPNAME=''sb_acl_rule_info'') THEN
		CREATE TYPE SB_ACL_RULE_INFO AS (
			rule_id INTEGER,
			action SB_ACL_RULE_TYPE
		);
	END IF;
END';